### ISSUE TITLE
co/contra-variance notation breaks scaps.

### ISSUE THREAD

**Issue by ShaneDelmore** [scala-search/scaps#14]
I was just playing around with Scaps, trying to figure out what kind of search would help me find reduce if I had never heard of it and I believe I may have stumbled across a bug.

This query works fine
GenTraversableOnce[A] => A
but this query returned an internal server error page
GenTraversableOnce[A] => +A
as did this
GenTraversableOnce[A] => A1
and this resulted in "end of input expected"
GenTraversableOnce[A] => [A]

**Comment by Luegg** [comment]
Thanks, there seems to be a general issue with unknown type identifiers in the current version.

In general, every identifier consisting of one character is interpreted as a type parameter. `+A` would be handled as a type named `+A`.

Can you describe a use case behind adding variance annotations to types/type parameter?
